export const VIDEOCHAT_FIELD_UPDATE = 'VIDEOCHAT_FIELD_UPDATE';
export const VIDEOCHAT_FIELD_ERROR = 'VIDEOCHAT_FIELD_ERROR';
export const VIDEOCHAT_FIELD_RESET = 'VIDEOCHAT_FIELD_RESET';
export const VIDEOCHAT_FIELD_RESET_VALUE = 'VIDEOCHAT_FIELD_RESET_VALUE';
